import React from 'react'
import { Sidebar, Header } from '../components/'
import Head from 'next/head'

export default function Home () {
  return (
    <>
      <Head>
        <title>Clon de Spotify</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Sidebar />
      <Header />
      <div className=''>
        <h1 className=''>Hola Mundo</h1>
      </div>
    </>
  )
}
