import React from 'react'
import Head from 'next/head'

import { useSelector } from 'react-redux'

import Loader from '../components/Loader/Loader'

export default function Home () {
  const { isLoading } = useSelector(state => state.profile)

  return (
    <>
      {/* <div className="animate-spin"></div> */}
      <Head>
        <title>Clon Spotify - Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {isLoading && <Loader />}
      {
        !isLoading && <div className="">
          <div className=''>
            <h1 className=''>Hola Mundo</h1>
          </div>
        </div>
      }
    </>
  )
}
